apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: customer-api-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: customer-api-config
                  key: SERVER_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: customer-api-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: customer-api-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: customer-api-config
                  key: DB_NAME
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""